blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^all/$', views.allEntries, name='allEntries'),
	url(r'^(?P<post_id>\d+)/$', views.detail, name='detail'),
	url(r'^(?P<post_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^(?P<post_id>\d+)/update/$', views.update, name='update'),
	url(r'^(?P<post_id>\d+)/delete/$', views.delete, name='delete'),
	url(r'^(?P<post_id>\d+)/comment/$', views.comment, name='comment'),
	url(r'^compose/$', views.compose, name='compose'),
	url(r'^create/$', views.create, name='create'),
	url(r'^login/$', views.userLogin, name='login'),
	url(r'^logout/$', views.userLogout, name='logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^create-user/$', views.createUser, name='createUser'),
	url(r'^login-required/$', views.loginRequired, name='loginRequired'),
)

emmaBlog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'emmaBlog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^$', 'blog.views.index', name='home'),
	url(r'^posts/', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^login/$', ),
)

blog/models.py
from django.db import models
from django.contrib import auth

class Post(models.Model):
	title = models.CharField(max_length=50)
	content = models.TextField()
	author = models.ForeignKey(auth.models.User)
	date = models.DateTimeField('date published')
	average_rating = models.IntegerField(null=True)

	def __unicode__(self):
		return self.title

class Comment(models.Model):
	author = models.CharField(max_length=50)
	comment = models.TextField()
	date = models.DateTimeField()
	post = models.ForeignKey(Post)

	def __unicode__(self):
		date = self.date.date()
		date = str(date)
		return "%s %s #%d"%(self.author, date, self.id)

class Rating(models.Model):
	post = models.ForeignKey(Post)
	value = models.IntegerField()
	rater = models.CharField(max_length=50)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.models import User 
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import authenticate, logout, login
from blog.models import Post, Comment

def index(request):
	posts = Post.objects.all().order_by('-date')[:4]
	return render(request, 'blog/index.html', {'posts':posts, 'user':request.user})

def allEntries(request):
	posts = Post.objects.all().order_by('-date')
	return render(request, 'blog/all-entries.html', {'posts':posts, 'user':request.user})

def detail(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	comments = post.comment_set.all()
	author = post.author.username
	date = str(post.date.date())
	context = {
		'post': post,
		'comments': comments,
		'author': author,
		'date': date,
		'user': request.user
	}
	return render(request, 'blog/post.html', context)

@login_required(login_url='/posts/login-required/')
def edit(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	return render(request, 'blog/edit.html', {'post':post, 'user':request.user})

def update(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	newTitle = request.POST['title']
	newContent = request.POST['content']
	post.title = newTitle
	post.content = newContent
	post.save()
	return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))

def create(request):
	title = request.POST['title']
	content = request.POST['content']
	date = timezone.now()
	post = Post(title=title, author=request.user, content=content, date=date)
	post.save()
	return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))

@login_required(login_url='/posts/login-required/')
def compose(request):
	return render(request, 'blog/compose.html', {'user':request.user})

def userLogin(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)
	if user:
		if user.is_active:
			login(request, user)
			return HttpResponseRedirect(reverse('blog:index'))
		else:
			#return render(request, 'blog/inactive.html', {'user':user})
			pass
	else:
		return render(request, 'blog/login-failed.html', {'username':username})

def userLogout(request):
	logout(request)
	return HttpResponseRedirect(reverse('blog:index'))

def register(request):
	return render(request, 'blog/register.html')

def createUser(request):
	username = request.POST['username']
	password = request.POST['password']
	user = User.objects.create_user(username, password=password)
	user.save()
	return HttpResponseRedirect(reverse('blog:index'))

def loginRequired(request):
	return render(request, 'blog/login-required.html')

@login_required(login_url='/posts/login-required')
def delete(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	post.comment_set.all().delete()
	post.delete()
	return HttpResponseRedirect(reverse('blog:index'))

def comment(request, post_id):
	author = request.POST['author']
	content = request.POST['comment']
	post = get_object_or_404(Post, pk=post_id)
	comment = Comment(author=author, comment=content, date=timezone.now(), post=post)
	comment.save()
	return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))

blog/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>Jeremy Estrada Blog Engine</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap-theme.min.css' %}" />
	</head>
	<body>
		{% block header %}
		<nav class="navbar navbar-default" role="navigation">
			<div class="navbar-header" id="header">
				<a class="navbar-brand" href="/"><span class="text-primary">Blog Engine (Blengine?)</span></a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'blog:index' %}">Home &nbsp <span class='glyphicon glyphicon-home'></span></a></li>
					<li><a href="{% url 'blog:allEntries' %}">All Entries</a></li>
					<li><a href="{% url 'blog:compose' %}">Compose</a></li>
				</ul>
				{% if user.is_authenticated %}
				<div class="navbar-right">
					<p>Welcome,<span class="text-primary"> {{user.username}}</span></p>
					<a href="{% url 'blog:logout' %}">Logout</a>
				</div>
				{% else %}
				<form class="navbar-form navbar-right" action="{% url 'blog:login' %}" method="post">
				{% csrf_token %}
					<input type="text" name="username" placeholder="username" class="form-control" />
					<input type="password" name="password" placeholder="password" class="form-control" />
					<input type="submit" value="Login" class="btn btn-default" />
				</form>
				<a class="navbar-right" href="{% url 'blog:register' %}">Register</a>
				{% endif %}
			</div>
		</nav>
		{% endblock %}
		<!--div class="breadcrumb"></div-->
		<div class="container" id="content">
		{% block content %}{% endblock %}
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
	</body>
</html>

blog/templates/blog/all-entries.html
{% extends "base.html" %}

{% block content %}
{% if posts %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="text-primary">All Entries</h4>
			</div>
			<div class="panel-body">
				{% for post in posts %}
				<div class="panel panel-default">
					<div class="panel-body">
						<h5><a href="{% url 'blog:detail'  post.id %}">{{ post.title }}</a></h5>
						<p>by <b>{{ post.author.username }}</b><br>{{ post.date.date }}</p>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% else %}
	<h3>Sorry. There are currently no blog posts.</h3>
{% endif %}
{% endblock %}

blog/templates/blog/compose.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="text-primary">Add Blog Entry</h4>
			</div>
			<div class="panel-body">
				<form action="{% url 'blog:create' %}" method="post">
				{% csrf_token %}
					Title: <input class="form-control" type="text" name="title" size="30"><br>
					Content: <textarea class="form-control" name="content" cols="80" rows="10"></textarea><br>
					<button class="btn btn-default" type="submit">Post</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="text-primary">Update Blog Post</h4>
			</div>
			<div class="panel-body">
				<form action="{% url 'blog:update' post.id %}" method="post">
				{% csrf_token %}
					Title: <input class="form-control" type="text" name="title" size="70" value="{{post.title}}"><br>
					<p>Author: <b>{{post.author.username}}</b></p>
					Content: <textarea class="form-control" name="content" cols="80" rows="10">{{post.content}}</textarea><br>
					<button class="btn btn-default" type="submit">Update Post</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
{% if posts %}
	{% for post in posts %}
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4><a href="{% url 'blog:detail'  post.id %}">{{ post.title }}</a></h4>
				</div>
				<div class="panel-body">
					<p>by <b>{{ post.author.username }}</b></p>
					<p>{{ post.date.date }}</p>
					<p>{{ post.content }}</p>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
{% else %}
	<h3>Sorry. There are currently no blog posts.</h3>
{% endif %}
{% endblock %}

blog/templates/blog/login-failed.html
{% extends 'base.html' %}

{% block content %}
<h3 class='text-warning'>Login Failed</h3>
<h4>Either the username or password provided are incorrect</h4>
{% endblock %}

blog/templates/blog/login-required.html
{% extends 'base.html' %}

{% block content %}
<h3>You must be logged in to perform this action</h3>
{% endblock %}

blog/templates/blog/post.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="text-primary">{{post.title}}</h4>
			</div>
			<div class="panel-body">
				<p>by <b>{{author}}</b></p>
				<p>{{post.date.date}}</p>
				<p>{{post.content}}</p>
			</div>
			<div class="panel-footer">
				<a href="{% url 'blog:edit' post.id %}"><button class="btn btn-default">Edit Post</button></a>
				<a href="{% url 'blog:delete' post.id %}"><button class="btn btn-default">Delete Post</button></a>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<h4>Comments:</h4>
	</div>
</div>
{% for comment in comments %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-info">
			<div class="panel-body">
				<p class="text-primary"><b>{{ comment.author }}</b></p>
				<p><b>{{ comment.date.date }}</b></p>
				<p>{{ comment.comment }}</p>
			</div>
		</div>
	</div>
</div>
{% endfor %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-body">
				<form action="{% url 'blog:comment' post.id %}" method="post">
				{% csrf_token %}
					Name: <input type="text" name="author" class="form-control"/><br>
					Comment: <textarea name="comment" class="form-control"></textarea><br>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="text-primary">Register New User</h4>
			</div>
			<div class="panel-body">
				<form action="{% url 'blog:createUser' %}" method='post'>
				{% csrf_token %}
					Username: <input type='text' name='username'class='form-control'/>
					Password: <input type='password' name='password' class='form-control'/>
					<br>
					<input type='submit' class='btn btn-default' value='Register' />
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}